version: 2

jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
      steps:
        - checkout
        - run:
          name: yarn install
          command: yarn install
        - run:
          name: test
          command: ./node_modules/.bin/cypress run -s cypress/integration/fusic/seike460_fusic.co.jp.js
