version: 2

jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - run: yarn install
      - run: ./node_modules/.bin/cypress run -s cypress/integration/fusic/seike460_fusic.co.jp.js
